/**
 * Portfólio VOID-9 / BalcãoIA — alinhado ao guia Hotmart painel.
 * Compliance: sem renda garantida; WhatsApp apenas ético/nominativo.
 */
import type { EbookIdea } from "./trends";

export type Void9Product = EbookIdea & {
  tier: 1 | 2 | 3;
  mechanism: string;
  bump: string;
  upsell: string;
  logoSlug: string;
  guaranteeDays: number;
};

export const VOID9_PORTFOLIO: Void9Product[] = [
  {
    slug: "foco-14",
    logoSlug: "foco-14",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_FOCO14",
    tier: 1,
    title: "FOCO 14 — Método de Foco Profissional",
    subtitle: "14 dias para eliminar distrações e produzir com evidência",
    promise:
      "Em 14 dias, elimine as principais distrações e feche cada dia com evidência do que avançou — sem virar monge.",
    bigIdea: "Método B.A.L.C.ÃO Foco: Bloqueio, Agenda, Lista 3, Check-out, Âncora, Output",
    mechanism: "B.A.L.C.ÃO Foco",
    price: 47,
    suggestedAffiliate: 50,
    guaranteeDays: 30,
    bump: "Planner FOCO 14 (R$27)",
    upsell: "Clareza Semanal (R$67)",
    alignedWithBalcaoia: true,
    chapters: [
      "A crise do foco na era digital",
      "Os 7 inimigos do foco",
      "O Método FOCO 14",
      "Fase 1 — Diagnóstico (dias 1-3)",
      "Fase 2 — Estrutura (dias 4-7)",
      "Fase 3 — Prática (dias 8-11)",
      "Fase 4 — Consolidação (dias 12-14)",
      "Ferramentas e recursos",
      "Plano de manutenção",
    ],
    painPoints: [
      "Dia cheio e pouca evidência do que saiu",
      "WhatsApp derruba qualquer bloco de foco",
      "Lista infinita sem prioridade",
      "Culpa noturna sem fechamento",
    ],
    benefits: [
      "Janelas de foco realistas",
      "Protocolo de 14 dias",
      "Check-out diário",
      "Bônus planner + áudios + checklist",
    ],
  },
  {
    slug: "rotina-clareza-freelancer",
    logoSlug: "rotina-clareza-freelancer",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_CLAREZA",
    tier: 1,
    title: "Clareza Semanal — Planejamento de Alta Performance",
    subtitle: "Ritual semanal para priorizar o que move a agulha",
    promise: "Pare de começar a semana no piloto automático com um ritual de planejamento aplicável.",
    bigIdea: "Ritual Clareza 4P: Pausar, Priorizar, Planejar, Proteger",
    mechanism: "Clareza 4P",
    price: 37,
    suggestedAffiliate: 50,
    guaranteeDays: 30,
    bump: "Templates Premium Semana (R$17)",
    upsell: "BalcãoIA Pro (R$97)",
    alignedWithBalcaoia: true,
    chapters: ["Diagnóstico", "4P", "Prioridade tripla", "Calendário", "Buffer", "Revisão", "Casos", "90 dias"],
    painPoints: ["Semana sem plano", "Troca constante de contexto", "Promessas demais"],
    benefits: ["Ritual semanal", "3 frentes claras", "Calendário realista"],
  },
  {
    slug: "checklist-atendimento-local",
    logoSlug: "checklist-atendimento-local",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_BALCAOIA_PRO",
    tier: 1,
    title: "BalcãoIA Pro — Atendimento Inteligente com IA",
    subtitle: "Atendimento com IA ética, simples e sem programar",
    promise: "Implemente atendimento assistido por IA no negócio local — com humano no comando.",
    bigIdea: "Prompts + triagem + follow-up ético",
    mechanism: "Atendimento IA Assistido",
    price: 97,
    suggestedAffiliate: 50,
    guaranteeDays: 30,
    bump: "Scripts de Atendimento Premium (R$37)",
    upsell: "Sistema BalcãoIA (R$197)",
    alignedWithBalcaoia: true,
    chapters: ["Fundamentos", "WhatsApp Business", "Prompts", "Triagem", "Follow-up", "Ferramentas", "Escala"],
    painPoints: ["Atendimento lento", "Tudo na mão", "Sem padrão de resposta"],
    benefits: ["50 prompts", "Fluxogramas", "Templates"],
  },
  {
    slug: "whatsapp-etico-negocios",
    logoSlug: "whatsapp-etico-negocios",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_WHATSAPP_ETICO",
    tier: 1,
    title: "WhatsApp Ético — Como Vender Mais Sem Spam",
    subtitle: "Vender no WhatsApp sem spam e sem gambiarra",
    promise: "Protocolo ético de consentimento, contexto e continuidade no WhatsApp.",
    bigIdea: "Consentimento → Contexto → Continuidade",
    mechanism: "3C Ético",
    price: 67,
    suggestedAffiliate: 50,
    guaranteeDays: 30,
    bump: "Biblioteca de 200 Mensagens (R$27)",
    upsell: "BalcãoIA Pro (R$97)",
    alignedWithBalcaoia: true,
    chapters: ["Mitos", "Consentimento", "Janelas", "Scripts", "Catálogo", "Follow-up", "LGPD", "Erros"],
    painPoints: ["Medo de ban", "Spam interno", "Respostas inconsistentes"],
    benefits: ["Regras claras", "Scripts éticos", "Janelas de resposta"],
  },
  {
    slug: "chatgpt-empreendedores",
    logoSlug: "chatgpt-empreendedores",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_CHATGPT",
    tier: 1,
    title: "ChatGPT para Empreendedores",
    subtitle: "Prompts e rotina prática para usar IA generativa no dia a dia do negócio",
    promise:
      "Estruture prompts com contexto real do seu negócio para obter respostas mais úteis do ChatGPT — sempre com revisão humana antes de usar.",
    bigIdea: "Prompt com contexto de negócio vence prompt genérico",
    mechanism: "Prompt com Contexto (PCC)",
    price: 57,
    suggestedAffiliate: 50,
    guaranteeDays: 30,
    bump: "Biblioteca de 50 Prompts Extra (R$27)",
    upsell: "BalcãoIA Pro (R$97)",
    alignedWithBalcaoia: true,
    chapters: [
      "O que o ChatGPT faz bem (e onde erra)",
      "Estrutura de um prompt com contexto",
      "Prompts para atendimento",
      "Prompts para conteúdo e redes",
      "Prompts para organização e planejamento",
      "Checklist de revisão antes de usar a resposta",
      "Erros comuns de quem começa",
      "Rotina semanal de uso",
    ],
    painPoints: [
      "Respostas genéricas que não servem para o seu negócio",
      "Não sabe o que perguntar",
      "Reescreve tudo do zero mesmo usando IA",
      "Medo de a IA inventar informação errada",
    ],
    benefits: [
      "Templates de prompt prontos por área",
      "Rotina semanal de uso",
      "Checklist de revisão humana",
      "Exemplos reais de negócio local",
    ],
  },
  {
    slug: "instagram-negocios-locais-ia",
    logoSlug: "instagram-negocios-locais-ia",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_INSTAGRAM",
    tier: 1,
    title: "Instagram para Negócios Locais com IA",
    subtitle: "Rotina de conteúdo para o Instagram do seu negócio, com apoio de IA e revisão humana",
    promise:
      "Monte uma rotina simples de conteúdo para o Instagram do seu negócio local usando IA para gerar ideias e rascunhos — sempre revisados antes de publicar.",
    bigIdea: "Consistência de conteúdo bate criatividade esporádica",
    mechanism: "Rotina de Conteúdo Assistido",
    price: 77,
    suggestedAffiliate: 50,
    guaranteeDays: 30,
    bump: "Banco de 100 Ideias de Post (R$27)",
    upsell: "Google Meu Negócio Masterclass (R$57)",
    alignedWithBalcaoia: true,
    chapters: [
      "Diagnóstico do seu Instagram hoje",
      "Definindo pilares de conteúdo",
      "Gerando ideias com IA (e revisando)",
      "Legendas e chamadas para ação",
      "Stories e Reels para negócio local",
      "Calendário editorial simples",
      "Métricas que importam de verdade",
      "Erros comuns de negócios locais",
      "Plano de 30 dias",
    ],
    painPoints: [
      "Posta sem estratégia e ninguém responde",
      "Falta de ideia toda semana",
      "Não sabe o que a IA pode ajudar de verdade",
      "Feed sem identidade visual clara",
    ],
    benefits: [
      "Pilares de conteúdo definidos",
      "Banco de ideias com IA",
      "Calendário editorial pronto",
      "Checklist de revisão antes de publicar",
    ],
  },
  {
    slug: "google-meu-negocio-masterclass",
    logoSlug: "google-meu-negocio-masterclass",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_GMN",
    tier: 1,
    title: "Google Meu Negócio Masterclass",
    subtitle: "Otimize seu perfil no Google para aparecer melhor nas buscas locais",
    promise:
      "Passo a passo para configurar e manter o perfil do Google Meu Negócio completo e atualizado — sem prometer primeira posição garantida.",
    bigIdea: "Perfil completo e atualizado importa mais que truque de última hora",
    mechanism: "Checklist GMN Completo",
    price: 57,
    suggestedAffiliate: 50,
    guaranteeDays: 30,
    bump: "Templates de Post para Google (R$17)",
    upsell: "Instagram para Negócios Locais com IA (R$77)",
    alignedWithBalcaoia: true,
    chapters: [
      "Por que o perfil incompleto custa clientes",
      "Cadastro e verificação corretos",
      "Categorias e atributos que ajudam a busca",
      "Fotos e horários sempre atualizados",
      "Respondendo avaliações com ética",
      "Posts e novidades no perfil",
      "Perguntas e respostas públicas",
      "Checklist mensal de manutenção",
    ],
    painPoints: [
      "Perfil desatualizado ou incompleto",
      "Não aparece nas buscas locais",
      "Não sabe responder avaliação negativa",
      "Esquece de manter horários corretos",
    ],
    benefits: [
      "Checklist de configuração completa",
      "Roteiros de resposta a avaliações",
      "Calendário de manutenção mensal",
      "Boas práticas sem prometer ranking garantido",
    ],
  },
  {
    slug: "10-prompts-whatsapp-vendem",
    logoSlug: "10-prompts-whatsapp-vendem",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_J1",
    tier: 1,
    title: "10 Prompts WhatsApp que Vendem",
    subtitle: "Prompts prontos para adaptar em conversas de venda no WhatsApp",
    promise:
      "10 prompts para gerar respostas de venda no WhatsApp — você adapta ao seu tom de voz e revisa antes de enviar.",
    bigIdea: "Prompt certo economiza tempo, não substitui o julgamento humano",
    mechanism: "Prompt Direto ao Ponto",
    price: 9,
    suggestedAffiliate: 70,
    guaranteeDays: 7,
    bump: "Biblioteca de 200 Mensagens (R$27)",
    upsell: "WhatsApp Ético — Como Vender Mais Sem Spam (R$67)",
    alignedWithBalcaoia: true,
    chapters: [
      "Como adaptar cada prompt ao seu negócio",
      "Prompt de primeira resposta",
      "Prompt de apresentação de produto",
      "Prompt de quebra de objeção de preço",
      "Prompt de fechamento sem pressão",
      "Prompt de follow-up ético",
      "Prompt de pós-venda",
      "Erros comuns ao copiar e colar",
    ],
    painPoints: [
      "Não sabe como começar a conversa",
      "Copia resposta genérica da internet",
      "Perde venda por demora na resposta",
      "Trava na objeção de preço",
    ],
    benefits: [
      "10 prompts prontos para adaptar",
      "Exemplos por segmento",
      "Alertas de revisão humana",
      "Uso imediato, sem curso longo",
    ],
  },
  {
    slug: "checklist-ia-1-hora",
    logoSlug: "checklist-ia-1-hora",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_J2",
    tier: 1,
    title: "Checklist IA em 1 Hora",
    subtitle: "Comece a usar IA no seu negócio em uma única hora de trabalho focado",
    promise:
      "Um checklist enxuto para organizar o mínimo necessário antes de usar IA no atendimento ou conteúdo — sem curso longo.",
    bigIdea: "Organização mínima viável antes da IA",
    mechanism: "Checklist 1H",
    price: 7,
    suggestedAffiliate: 70,
    guaranteeDays: 7,
    bump: "Mini-Guia GMN 30 min (R$9)",
    upsell: "BalcãoIA Pro (R$97)",
    alignedWithBalcaoia: true,
    chapters: [
      "O que organizar antes de usar IA",
      "Catálogo e preços em um só lugar",
      "Política de atendimento em 5 linhas",
      "Primeiro prompt de teste",
      "Checklist final de 1 hora",
      "Próximos passos depois da hora 1",
    ],
    painPoints: [
      "Não sabe por onde começar com IA",
      "Acha que precisa de curso longo antes de testar",
      "Informação espalhada em vários lugares",
      "Medo de usar IA e errar com o cliente",
    ],
    benefits: [
      "Checklist de 1 hora, direto ao ponto",
      "Sem jargão técnico",
      "Base pronta para evoluir depois",
      "Foco em revisão humana",
    ],
  },
  {
    slug: "30-posts-prontos-ia",
    logoSlug: "30-posts-prontos-ia",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_J3",
    tier: 1,
    title: "30 Posts Prontos com IA",
    subtitle: "30 estruturas de post para adaptar ao seu negócio, com apoio de IA e revisão",
    promise:
      "30 estruturas de legenda e post para você adaptar — já revisadas quanto à clareza e ao tom, sem prometer viralização.",
    bigIdea: "Estrutura pronta economiza a parte mais difícil: começar",
    mechanism: "Banco de Estruturas",
    price: 12,
    suggestedAffiliate: 70,
    guaranteeDays: 7,
    bump: "20 Legendas Instagram por Segmento (R$7)",
    upsell: "Instagram para Negócios Locais com IA (R$77)",
    alignedWithBalcaoia: true,
    chapters: [
      "Como adaptar cada estrutura ao seu negócio",
      "10 posts de apresentação e bastidores",
      "10 posts de prova social ética",
      "10 posts de oferta e chamada para ação",
      "Checklist antes de publicar",
      "Erros comuns ao usar IA em conteúdo",
    ],
    painPoints: [
      "Não sabe o que postar essa semana",
      "Texto de IA sai genérico",
      "Feed sem consistência",
      "Perde tempo criando do zero",
    ],
    benefits: [
      "30 estruturas prontas para adaptar",
      "Organizadas por objetivo",
      "Checklist de revisão",
      "Uso imediato no seu perfil",
    ],
  },
  {
    slug: "template-atendimento-automatico",
    logoSlug: "template-atendimento-automatico",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_J4",
    tier: 1,
    title: "Template Atendimento Automático Ético",
    subtitle: "Estrutura de respostas rápidas para organizar o atendimento sem robôs enganosos",
    promise:
      "Template de respostas rápidas e fluxo de triagem para organizar seu atendimento — sem automação não oficial de WhatsApp.",
    bigIdea: "Padrão de resposta bem escrito substitui robô arriscado",
    mechanism: "Fluxo de Triagem Ético",
    price: 14,
    suggestedAffiliate: 70,
    guaranteeDays: 7,
    bump: "10 Prompts WhatsApp que Vendem (R$9)",
    upsell: "BalcãoIA Pro (R$97)",
    alignedWithBalcaoia: true,
    chapters: [
      "Por que evitar automação não oficial",
      "Mapa de triagem por tipo de pergunta",
      "Templates de primeira resposta",
      "Templates de horário e disponibilidade",
      "Templates de encaminhamento interno",
      "Checklist de revisão da equipe",
    ],
    painPoints: [
      "Cada atendente responde diferente",
      "Medo de usar robô e tomar bloqueio",
      "Demora para responder o básico",
      "Sem padrão para novos atendentes",
    ],
    benefits: [
      "Templates prontos para copiar",
      "Fluxo de triagem simples",
      "Sem automação arriscada",
      "Fácil de treinar equipe nova",
    ],
  },
  {
    slug: "mini-guia-gmn-30min",
    logoSlug: "mini-guia-gmn-30min",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_J5",
    tier: 1,
    title: "Mini-Guia GMN 30 min",
    subtitle: "Ajuste rápido do seu perfil no Google Meu Negócio em meia hora",
    promise:
      "Guia enxuto com os ajustes de maior impacto no seu perfil do Google Meu Negócio, para aplicar em cerca de 30 minutos.",
    bigIdea: "Poucos ajustes certos valem mais que mexer em tudo",
    mechanism: "Ajuste Rápido GMN",
    price: 9,
    suggestedAffiliate: 70,
    guaranteeDays: 7,
    bump: "Checklist IA em 1 Hora (R$7)",
    upsell: "Google Meu Negócio Masterclass (R$57)",
    alignedWithBalcaoia: true,
    chapters: [
      "Os 5 ajustes de maior impacto",
      "Categoria e atributos corretos",
      "Fotos mínimas que fazem diferença",
      "Horário e informações de contato",
      "Checklist final de 30 minutos",
    ],
    painPoints: [
      "Perfil abandonado há meses",
      "Não sabe o que priorizar",
      "Pouco tempo disponível",
      "Acha que precisa mexer em tudo de uma vez",
    ],
    benefits: [
      "Ajustes priorizados por impacto",
      "Guia rápido de 30 minutos",
      "Sem promessa de ranking garantido",
      "Ponte para o Masterclass completo",
    ],
  },
  {
    slug: "20-legendas-instagram",
    logoSlug: "20-legendas-instagram",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_J6",
    tier: 1,
    title: "20 Legendas Instagram por Segmento",
    subtitle: "Legendas prontas para adaptar por segmento de negócio local",
    promise:
      "20 legendas organizadas por segmento de negócio local para você adaptar ao seu tom de voz — não são garantia de engajamento.",
    bigIdea: "Legenda pronta bem adaptada bate legenda genérica",
    mechanism: "Banco de Legendas por Segmento",
    price: 7,
    suggestedAffiliate: 70,
    guaranteeDays: 7,
    bump: "30 Posts Prontos com IA (R$12)",
    upsell: "Instagram para Negócios Locais com IA (R$77)",
    alignedWithBalcaoia: true,
    chapters: [
      "Como adaptar a legenda ao seu segmento",
      "Legendas para bastidores e apresentação",
      "Legendas para prova social ética",
      "Legendas para oferta e chamada",
      "Checklist antes de publicar",
    ],
    painPoints: [
      "Não sabe como escrever a legenda",
      "Legenda genérica não conecta com o público",
      "Perde tempo pensando no texto",
      "Falta de identidade no que escreve",
    ],
    benefits: [
      "20 legendas prontas para adaptar",
      "Organizadas por segmento",
      "Checklist de revisão",
      "Uso imediato",
    ],
  },
  {
    slug: "calculadora-preco-rapida",
    logoSlug: "calculadora-preco-rapida",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_J7",
    tier: 1,
    title: "Calculadora de Preço Rápida",
    subtitle: "Planilha simples para precificar produtos e serviços com base em custo e margem",
    promise:
      "Uma planilha para calcular preço mínimo viável considerando custo, tempo e margem — não é consultoria financeira.",
    bigIdea: "Preço sem cálculo é aposta, não estratégia",
    mechanism: "Planilha Custo + Margem",
    price: 9,
    suggestedAffiliate: 70,
    guaranteeDays: 7,
    bump: "Checklist IA em 1 Hora (R$7)",
    upsell: "BalcãoIA Pro (R$97)",
    alignedWithBalcaoia: true,
    chapters: [
      "Por que preço no achismo custa caro",
      "Mapeando custos reais",
      "Definindo margem mínima",
      "Usando a planilha passo a passo",
      "Revisando preço periodicamente",
    ],
    painPoints: [
      "Precifica no chute",
      "Não sabe se está tendo lucro de verdade",
      "Concorrente mais barato assusta",
      "Nunca revisou o preço desde que começou",
    ],
    benefits: [
      "Planilha pronta para usar",
      "Cálculo de margem simples",
      "Rotina de revisão de preço",
      "Sem promessa de resultado financeiro",
    ],
  },
  {
    slug: "15-ideias-reels-segmento",
    logoSlug: "15-ideias-reels-segmento",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_J8",
    tier: 1,
    title: "15 Ideias de Reels por Segmento",
    subtitle: "Roteiros curtos de Reels adaptáveis ao seu tipo de negócio",
    promise:
      "15 roteiros curtos de Reels organizados por segmento de negócio local, para você gravar e adaptar — sem promessa de viralização.",
    bigIdea: "Roteiro pronto elimina o bloqueio de gravação",
    mechanism: "Banco de Roteiros Reels",
    price: 7,
    suggestedAffiliate: 70,
    guaranteeDays: 7,
    bump: "20 Legendas Instagram por Segmento (R$7)",
    upsell: "Instagram para Negócios Locais com IA (R$77)",
    alignedWithBalcaoia: true,
    chapters: [
      "Como adaptar o roteiro ao seu segmento",
      "Roteiros de bastidores",
      "Roteiros de dica rápida",
      "Roteiros de antes e depois (uso próprio, sem prometer resultado)",
      "Checklist de gravação simples",
    ],
    painPoints: [
      "Trava na hora de gravar",
      "Não sabe o que falar no vídeo",
      "Acha que precisa de equipamento caro",
      "Sem tempo para planejar roteiro",
    ],
    benefits: [
      "15 roteiros prontos para gravar",
      "Organizados por segmento",
      "Gravação com celular já basta",
      "Checklist simples de produção",
    ],
  },
  {
    slug: "template-bio-instagram",
    logoSlug: "template-bio-instagram",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_J9",
    tier: 1,
    title: "Template Bio Instagram Perfeita",
    subtitle: "Estrutura para escrever uma bio clara no Instagram do seu negócio",
    promise:
      "Um template estruturado para escrever a bio do Instagram do seu negócio com clareza — o que você faz, para quem e o próximo passo.",
    bigIdea: "Bio confusa perde cliente antes mesmo do primeiro post",
    mechanism: "Estrutura de Bio Clara",
    price: 7,
    suggestedAffiliate: 70,
    guaranteeDays: 7,
    bump: "15 Ideias de Reels por Segmento (R$7)",
    upsell: "Instagram para Negócios Locais com IA (R$77)",
    alignedWithBalcaoia: true,
    chapters: [
      "Os 4 elementos de uma bio clara",
      "Exemplos por tipo de negócio local",
      "Escolhendo o link certo",
      "Erros comuns de bio",
      "Checklist final antes de publicar",
    ],
    painPoints: [
      "Bio genérica ou vazia",
      "Visitante não entende o que o negócio faz",
      "Não sabe o que colocar no link",
      "Nunca revisou a bio desde que criou o perfil",
    ],
    benefits: [
      "Template pronto para preencher",
      "Exemplos por segmento",
      "Checklist de revisão",
      "Aplicação em minutos",
    ],
  },
  {
    slug: "pack-50-hashtags-nicho",
    logoSlug: "pack-50-hashtags-nicho",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_J10",
    tier: 1,
    title: "Pack 50 Hashtags por Nicho",
    subtitle: "Listas de hashtags organizadas por nicho de negócio local",
    promise:
      "50 hashtags organizadas por nicho de negócio local para usar como ponto de partida — não garantem alcance ou engajamento.",
    bigIdea: "Hashtag organizada por nicho bate hashtag genérica copiada",
    mechanism: "Curadoria por Nicho",
    price: 7,
    suggestedAffiliate: 70,
    guaranteeDays: 7,
    bump: "Template Bio Instagram Perfeita (R$7)",
    upsell: "Instagram para Negócios Locais com IA (R$77)",
    alignedWithBalcaoia: true,
    chapters: [
      "Como escolher hashtags por nicho",
      "Lista para serviços locais",
      "Lista para comércio e varejo",
      "Lista para saúde e bem-estar (uso educativo)",
      "Como testar e revisar o desempenho",
    ],
    painPoints: [
      "Usa sempre as mesmas hashtags genéricas",
      "Não sabe quais funcionam para o seu nicho",
      "Acha que hashtag sozinha resolve alcance",
      "Nunca testou combinações diferentes",
    ],
    benefits: [
      "50 hashtags organizadas por nicho",
      "Ponto de partida para testar",
      "Sem promessa de alcance garantido",
      "Fácil de copiar e colar",
    ],
  },
  {
    slug: "desafio-7d-atendimento",
    logoSlug: "desafio-7d-atendimento",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_PRODUTIVIDADE",
    tier: 1,
    title: "Produtividade Local — Gestão Inteligente para Empreendedores",
    subtitle: "Pare de apagar incêndios e organize o negócio",
    promise: "Sistema para recuperar tempo e criar processos simples no negócio local.",
    bigIdea: "Mapear → Delegar → Automatizar o óbvio",
    mechanism: "Gestão Local",
    price: 87,
    suggestedAffiliate: 50,
    guaranteeDays: 30,
    bump: "Kit Ferramentas Premium (R$27)",
    upsell: "Sistema BalcãoIA (R$197)",
    alignedWithBalcaoia: true,
    chapters: ["Diagnóstico", "Mapa de tarefas", "Delegação", "Processos", "Ferramentas", "Metas", "Rotinas"],
    painPoints: ["Faz tudo sozinho", "Sem processo", "Dia caótico"],
    benefits: ["Mapa de processos", "Checklists", "Kit ferramentas"],
  },
  {
    slug: "curso-organizacao-atendimento",
    logoSlug: "curso-organizacao-atendimento",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_SISTEMA",
    tier: 2,
    title: "Sistema BalcãoIA — Curso Completo de IA para Negócios Locais",
    subtitle: "Do zero ao avançado, sem precisar programar",
    promise: "Curso modular para implementar IA no negócio local com prática em cada aula.",
    bigIdea: "7 módulos de implantação real",
    mechanism: "Sistema BalcãoIA",
    price: 197,
    suggestedAffiliate: 40,
    guaranteeDays: 30,
    bump: "Suporte Premium 30 dias (R$47)",
    upsell: "Transformação Digital Local (R$297)",
    alignedWithBalcaoia: true,
    chapters: ["Fundamentos", "WhatsApp", "Marketing", "Processos", "Vendas", "Dados", "Escala"],
    painPoints: ["Não sabe por onde começar com IA", "Cursos genéricos", "Sem implementação"],
    benefits: ["Módulos práticos", "Templates", "Comunidade"],
  },
  {
    slug: "programa-8-semanas-balcao",
    logoSlug: "programa-8-semanas-balcao",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_TRANSFORMACAO",
    tier: 2,
    title: "Transformação Digital Local — Programa de 8 Semanas",
    subtitle: "Digitalização semana a semana com tarefas práticas",
    promise: "8 semanas de implantação digital com checklists e resultado mensurável.",
    bigIdea: "Trilha 8S BalcãoIA",
    mechanism: "8S BalcãoIA",
    price: 297,
    suggestedAffiliate: 40,
    guaranteeDays: 30,
    bump: "Comunidade Premium (R$67)",
    upsell: "Método BalcãoIA (R$247)",
    alignedWithBalcaoia: true,
    chapters: ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8"],
    painPoints: ["Começa e para", "Sem ritmo", "Sem métrica"],
    benefits: ["Trilha semanal", "Tarefas", "Suporte 8 semanas"],
  },
  {
    slug: "sistema-balcao-proprietario",
    logoSlug: "sistema-balcao-proprietario",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_METODO",
    tier: 2,
    title: "Método BalcãoIA — O Sistema Proprietário Completo",
    subtitle: "4 pilares para o balcão digital com IA",
    promise: "Método proprietário: Diagnóstico → Estrutura → Automação → Crescimento.",
    bigIdea: "4 Pilares BalcãoIA",
    mechanism: "4 Pilares",
    price: 247,
    suggestedAffiliate: 40,
    guaranteeDays: 30,
    bump: "Licença Comercial (R$97)",
    upsell: "Workshop IA Local (R$197)",
    alignedWithBalcaoia: true,
    chapters: ["Diagnóstico", "Estrutura", "Automação", "Crescimento", "Workbook", "Checklist"],
    painPoints: ["Sem sistema", "Tudo na cabeça", "Métodos genéricos"],
    benefits: ["Workbook", "Mapas mentais", "Checklist por fase"],
  },
  {
    slug: "workshop-ia-atendimento",
    logoSlug: "workshop-ia-atendimento",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_WORKSHOP",
    tier: 2,
    title: "Workshop IA para Negócios Locais — Implementação Prática",
    subtitle: "Hands-on: implemente no mesmo dia",
    promise: "Workshop gravado com implementação prática de IA no negócio local.",
    bigIdea: "Loop Prompt → Revisar → Registrar",
    mechanism: "Loop PRR",
    price: 197,
    suggestedAffiliate: 40,
    guaranteeDays: 30,
    bump: "Gravação HD + Extra (R$47)",
    upsell: "Bundle Master (R$397)",
    alignedWithBalcaoia: true,
    chapters: ["Limites da IA", "Prompts", "Triagem", "Conteúdo", "Follow-up", "Relatório"],
    painPoints: ["Teoria demais", "Sem prática", "IA inventa"],
    benefits: ["Gravação HD", "Templates", "Suporte 15 dias"],
  },
  {
    slug: "bundle-entrada-local",
    logoSlug: "bundle-entrada-local",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_BUNDLE",
    tier: 2,
    title: "Bundle Master BalcãoIA — Pacote Completo de Entrada",
    subtitle: "5 produtos de entrada com desconto",
    promise: "FOCO 14 + Clareza + BalcãoIA Pro + WhatsApp Ético + Produtividade Local.",
    bigIdea: "Trilha Entrada",
    mechanism: "Trilha Entrada",
    price: 197,
    suggestedAffiliate: 40,
    guaranteeDays: 30,
    bump: "Mentoria em Grupo 1 sessão (R$97)",
    upsell: "Sistema BalcãoIA (R$197)",
    alignedWithBalcaoia: true,
    chapters: ["Como usar", "Ordem", "21 dias", "Sinergia", "Próximo passo"],
    painPoints: ["Não sabe por onde começar", "Compra isolada"],
    benefits: ["Ordem clara", "Economia de trilha", "Base sólida"],
  },
  {
    slug: "mentoria-grupo-gravada",
    logoSlug: "mentoria-grupo-gravada",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_MENTORIA",
    tier: 3,
    title: "Mentoria BalcãoIA em Grupo — Implementação Guiada",
    subtitle: "3 meses de implementação guiada gravada",
    promise: "Mentoria gravada com diagnóstico, plano de ação e comunidade.",
    bigIdea: "Ciclo Mentoria → Tarefa → Revisão",
    mechanism: "Ciclo MTR",
    price: 997,
    suggestedAffiliate: 30,
    guaranteeDays: 15,
    bump: "Análise Individual do Negócio (R$197)",
    upsell: "Curso Avançado + Comunidade (R$1497)",
    alignedWithBalcaoia: true,
    chapters: ["Expectativa", "Diagnóstico", "Operação", "Oferta", "Tempo", "Métricas", "30 dias", "FAQ"],
    painPoints: ["Sozinho na implantação", "Sem revisão", "Travamento"],
    benefits: ["Playbooks", "Ciclo de tarefa", "Gravações"],
  },
  {
    slug: "curso-avancado-comunidade",
    logoSlug: "curso-avancado-comunidade",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_AVANCADO",
    tier: 3,
    title: "Curso Avançado BalcãoIA + Comunidade de Alto Nível",
    subtitle: "Operação avançada com peer review",
    promise: "Nível avançado + comunidade de operadores locais.",
    bigIdea: "Trilha Avançada + Peer Review",
    mechanism: "Peer Review",
    price: 1497,
    suggestedAffiliate: 30,
    guaranteeDays: 15,
    bump: "Revisão Mensal de Estratégia (R$297)",
    upsell: "Certificação BalcãoIA (R$1997)",
    alignedWithBalcaoia: true,
    chapters: ["Operação", "Papéis", "IA governança", "Ofertas", "Retenção", "Comunidade", "Projetos", "Avaliação"],
    painPoints: ["Estagnou no básico", "Sem pares", "Governança fraca"],
    benefits: ["Nível avançado", "Comunidade", "Projetos"],
  },
  {
    slug: "certificado-conclusao-7d",
    logoSlug: "certificado-conclusao-7d",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_CERTIFICACAO",
    tier: 3,
    title: "Certificação BalcãoIA — Especialista em IA para Negócios Locais",
    subtitle: "Credencial por evidência de implantação",
    promise: "Certificação por portfólio operacional — não diploma vazio.",
    bigIdea: "Portfólio Operacional",
    mechanism: "Prova por Portfólio",
    price: 1997,
    suggestedAffiliate: 30,
    guaranteeDays: 15,
    bump: "Kit de Prospecção Completo (R$197)",
    upsell: "Mastermind BalcãoIA (R$2497)",
    alignedWithBalcaoia: true,
    chapters: ["Critérios", "Teoria", "Prática", "Portfólio", "Rubrica", "Defesa", "Manutenção"],
    painPoints: ["Quer credencial vazia", "Sem evidência", "Sem padrão"],
    benefits: ["Rubrica clara", "Portfólio", "Selo por evidência"],
  },
  {
    slug: "mastermind-gravado-operadores",
    logoSlug: "mastermind-gravado-operadores",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_MASTERMIND",
    tier: 3,
    title: "Mastermind BalcãoIA — Grupo Seleto de Alto Nível",
    subtitle: "Rodadas de decisão e accountability",
    promise: "Mastermind gravado para quem já tem base e quer escala ética.",
    bigIdea: "Rodadas de Decisão",
    mechanism: "Rodadas + Accountability",
    price: 2497,
    suggestedAffiliate: 30,
    guaranteeDays: 15,
    bump: "Consultoria Individual 1h extra (R$497)",
    upsell: "Suite Completa (R$2997)",
    alignedWithBalcaoia: true,
    chapters: ["Regras", "Oferta", "Operação", "Tempo", "Pessoas", "Trimestre", "Ética"],
    painPoints: ["Decisões isoladas", "Sem pares sérios", "Escala bagunçada"],
    benefits: ["Rodadas", "Accountability", "Ética de marca"],
  },
  {
    slug: "suite-completa-balcaoia",
    logoSlug: "foco-14",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_SUITE",
    tier: 3,
    title: "Suite Completa BalcãoIA — Acesso Total e Vitalício",
    subtitle: "Todo o ecossistema em um investimento único",
    promise: "Acesso vitalício a todos os produtos do ecossistema BalcãoIA.",
    bigIdea: "Acesso Total",
    mechanism: "Suite Vitalícia",
    price: 2997,
    suggestedAffiliate: 30,
    guaranteeDays: 30,
    bump: "Licença de Revenda (R$997)",
    upsell: "N/A (produto topo)",
    alignedWithBalcaoia: true,
    chapters: ["O que inclui", "Ordem de uso", "Comunidade", "Suporte", "Atualizações"],
    painPoints: ["Não quer escolher", "Compra fragmentada", "Quer acesso total"],
    benefits: ["14 produtos", "Atualizações", "Suporte prioritário"],
  },
];

export function getVoid9BySlug(slug: string) {
  return VOID9_PORTFOLIO.find((p) => p.slug === slug) ?? null;
}

export function getVoid9AsEbookIdeas(): Array<EbookIdea & { nicheName: string; nicheId: string }> {
  return VOID9_PORTFOLIO.map((p) => ({
    ...p,
    nicheName: `BalcãoIA Tier ${p.tier}`,
    nicheId: "void9-balcaoia",
  }));
}
