/**
 * Portfólio VOID-9 / BalcãoIA — alinhado ao guia Hotmart painel.
 * Compliance: sem renda garantida; WhatsApp apenas ético/nominativo.
 */
import type { EbookIdea } from "./trends";

export type Void9Product = EbookIdea & {
  tier: 1 | 2 | 3;
  mechanism: string;
  bump: string;
  upsell: string;
  logoSlug: string;
  guaranteeDays: number;
};

export const VOID9_PORTFOLIO: Void9Product[] = [
  {
    slug: "foco-14",
    logoSlug: "foco-14",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_FOCO14",
    tier: 1,
    title: "FOCO 14 — Método de Foco Profissional",
    subtitle: "14 dias para eliminar distrações e produzir com evidência",
    promise:
      "Em 14 dias, elimine as principais distrações e feche cada dia com evidência do que avançou — sem virar monge.",
    bigIdea: "Método B.A.L.C.ÃO Foco: Bloqueio, Agenda, Lista 3, Check-out, Âncora, Output",
    mechanism: "B.A.L.C.ÃO Foco",
    price: 47,
    suggestedAffiliate: 50,
    guaranteeDays: 30,
    bump: "Planner FOCO 14 (R$27)",
    upsell: "Clareza Semanal (R$67)",
    alignedWithBalcaoia: true,
    chapters: [
      "A crise do foco na era digital",
      "Os 7 inimigos do foco",
      "O Método FOCO 14",
      "Fase 1 — Diagnóstico (dias 1-3)",
      "Fase 2 — Estrutura (dias 4-7)",
      "Fase 3 — Prática (dias 8-11)",
      "Fase 4 — Consolidação (dias 12-14)",
      "Ferramentas e recursos",
      "Plano de manutenção",
    ],
    painPoints: [
      "Dia cheio e pouca evidência do que saiu",
      "WhatsApp derruba qualquer bloco de foco",
      "Lista infinita sem prioridade",
      "Culpa noturna sem fechamento",
    ],
    benefits: [
      "Janelas de foco realistas",
      "Protocolo de 14 dias",
      "Check-out diário",
      "Bônus planner + áudios + checklist",
    ],
  },
  {
    slug: "rotina-clareza-freelancer",
    logoSlug: "rotina-clareza-freelancer",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_CLAREZA",
    tier: 1,
    title: "Clareza Semanal — Planejamento de Alta Performance",
    subtitle: "Ritual semanal para priorizar o que move a agulha",
    promise: "Pare de começar a semana no piloto automático com um ritual de planejamento aplicável.",
    bigIdea: "Ritual Clareza 4P: Pausar, Priorizar, Planejar, Proteger",
    mechanism: "Clareza 4P",
    price: 37,
    suggestedAffiliate: 50,
    guaranteeDays: 30,
    bump: "Templates Premium Semana (R$17)",
    upsell: "BalcãoIA Pro (R$97)",
    alignedWithBalcaoia: true,
    chapters: ["Diagnóstico", "4P", "Prioridade tripla", "Calendário", "Buffer", "Revisão", "Casos", "90 dias"],
    painPoints: ["Semana sem plano", "Troca constante de contexto", "Promessas demais"],
    benefits: ["Ritual semanal", "3 frentes claras", "Calendário realista"],
  },
  {
    slug: "checklist-atendimento-local",
    logoSlug: "checklist-atendimento-local",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_BALCAOIA_PRO",
    tier: 1,
    title: "BalcãoIA Pro — Atendimento Inteligente com IA",
    subtitle: "Atendimento com IA ética, simples e sem programar",
    promise: "Implemente atendimento assistido por IA no negócio local — com humano no comando.",
    bigIdea: "Prompts + triagem + follow-up ético",
    mechanism: "Atendimento IA Assistido",
    price: 97,
    suggestedAffiliate: 50,
    guaranteeDays: 30,
    bump: "Scripts de Atendimento Premium (R$37)",
    upsell: "Sistema BalcãoIA (R$197)",
    alignedWithBalcaoia: true,
    chapters: ["Fundamentos", "WhatsApp Business", "Prompts", "Triagem", "Follow-up", "Ferramentas", "Escala"],
    painPoints: ["Atendimento lento", "Tudo na mão", "Sem padrão de resposta"],
    benefits: ["50 prompts", "Fluxogramas", "Templates"],
  },
  {
    slug: "whatsapp-etico-negocios",
    logoSlug: "whatsapp-etico-negocios",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_WHATSAPP_ETICO",
    tier: 1,
    title: "WhatsApp Ético — Como Vender Mais Sem Spam",
    subtitle: "Vender no WhatsApp sem spam e sem gambiarra",
    promise: "Protocolo ético de consentimento, contexto e continuidade no WhatsApp.",
    bigIdea: "Consentimento → Contexto → Continuidade",
    mechanism: "3C Ético",
    price: 67,
    suggestedAffiliate: 50,
    guaranteeDays: 30,
    bump: "Biblioteca de 200 Mensagens (R$27)",
    upsell: "BalcãoIA Pro (R$97)",
    alignedWithBalcaoia: true,
    chapters: ["Mitos", "Consentimento", "Janelas", "Scripts", "Catálogo", "Follow-up", "LGPD", "Erros"],
    painPoints: ["Medo de ban", "Spam interno", "Respostas inconsistentes"],
    benefits: ["Regras claras", "Scripts éticos", "Janelas de resposta"],
  },
  {
    slug: "desafio-7d-atendimento",
    logoSlug: "desafio-7d-atendimento",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_PRODUTIVIDADE",
    tier: 1,
    title: "Produtividade Local — Gestão Inteligente para Empreendedores",
    subtitle: "Pare de apagar incêndios e organize o negócio",
    promise: "Sistema para recuperar tempo e criar processos simples no negócio local.",
    bigIdea: "Mapear → Delegar → Automatizar o óbvio",
    mechanism: "Gestão Local",
    price: 87,
    suggestedAffiliate: 50,
    guaranteeDays: 30,
    bump: "Kit Ferramentas Premium (R$27)",
    upsell: "Sistema BalcãoIA (R$197)",
    alignedWithBalcaoia: true,
    chapters: ["Diagnóstico", "Mapa de tarefas", "Delegação", "Processos", "Ferramentas", "Metas", "Rotinas"],
    painPoints: ["Faz tudo sozinho", "Sem processo", "Dia caótico"],
    benefits: ["Mapa de processos", "Checklists", "Kit ferramentas"],
  },
  {
    slug: "curso-organizacao-atendimento",
    logoSlug: "curso-organizacao-atendimento",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_SISTEMA",
    tier: 2,
    title: "Sistema BalcãoIA — Curso Completo de IA para Negócios Locais",
    subtitle: "Do zero ao avançado, sem precisar programar",
    promise: "Curso modular para implementar IA no negócio local com prática em cada aula.",
    bigIdea: "7 módulos de implantação real",
    mechanism: "Sistema BalcãoIA",
    price: 197,
    suggestedAffiliate: 40,
    guaranteeDays: 30,
    bump: "Suporte Premium 30 dias (R$47)",
    upsell: "Transformação Digital Local (R$297)",
    alignedWithBalcaoia: true,
    chapters: ["Fundamentos", "WhatsApp", "Marketing", "Processos", "Vendas", "Dados", "Escala"],
    painPoints: ["Não sabe por onde começar com IA", "Cursos genéricos", "Sem implementação"],
    benefits: ["Módulos práticos", "Templates", "Comunidade"],
  },
  {
    slug: "programa-8-semanas-balcao",
    logoSlug: "programa-8-semanas-balcao",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_TRANSFORMACAO",
    tier: 2,
    title: "Transformação Digital Local — Programa de 8 Semanas",
    subtitle: "Digitalização semana a semana com tarefas práticas",
    promise: "8 semanas de implantação digital com checklists e resultado mensurável.",
    bigIdea: "Trilha 8S BalcãoIA",
    mechanism: "8S BalcãoIA",
    price: 297,
    suggestedAffiliate: 40,
    guaranteeDays: 30,
    bump: "Comunidade Premium (R$67)",
    upsell: "Método BalcãoIA (R$247)",
    alignedWithBalcaoia: true,
    chapters: ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8"],
    painPoints: ["Começa e para", "Sem ritmo", "Sem métrica"],
    benefits: ["Trilha semanal", "Tarefas", "Suporte 8 semanas"],
  },
  {
    slug: "sistema-balcao-proprietario",
    logoSlug: "sistema-balcao-proprietario",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_METODO",
    tier: 2,
    title: "Método BalcãoIA — O Sistema Proprietário Completo",
    subtitle: "4 pilares para o balcão digital com IA",
    promise: "Método proprietário: Diagnóstico → Estrutura → Automação → Crescimento.",
    bigIdea: "4 Pilares BalcãoIA",
    mechanism: "4 Pilares",
    price: 247,
    suggestedAffiliate: 40,
    guaranteeDays: 30,
    bump: "Licença Comercial (R$97)",
    upsell: "Workshop IA Local (R$197)",
    alignedWithBalcaoia: true,
    chapters: ["Diagnóstico", "Estrutura", "Automação", "Crescimento", "Workbook", "Checklist"],
    painPoints: ["Sem sistema", "Tudo na cabeça", "Métodos genéricos"],
    benefits: ["Workbook", "Mapas mentais", "Checklist por fase"],
  },
  {
    slug: "workshop-ia-atendimento",
    logoSlug: "workshop-ia-atendimento",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_WORKSHOP",
    tier: 2,
    title: "Workshop IA para Negócios Locais — Implementação Prática",
    subtitle: "Hands-on: implemente no mesmo dia",
    promise: "Workshop gravado com implementação prática de IA no negócio local.",
    bigIdea: "Loop Prompt → Revisar → Registrar",
    mechanism: "Loop PRR",
    price: 197,
    suggestedAffiliate: 40,
    guaranteeDays: 30,
    bump: "Gravação HD + Extra (R$47)",
    upsell: "Bundle Master (R$397)",
    alignedWithBalcaoia: true,
    chapters: ["Limites da IA", "Prompts", "Triagem", "Conteúdo", "Follow-up", "Relatório"],
    painPoints: ["Teoria demais", "Sem prática", "IA inventa"],
    benefits: ["Gravação HD", "Templates", "Suporte 15 dias"],
  },
  {
    slug: "bundle-entrada-local",
    logoSlug: "bundle-entrada-local",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_BUNDLE",
    tier: 2,
    title: "Bundle Master BalcãoIA — Pacote Completo de Entrada",
    subtitle: "5 produtos de entrada com desconto",
    promise: "FOCO 14 + Clareza + BalcãoIA Pro + WhatsApp Ético + Produtividade Local.",
    bigIdea: "Trilha Entrada",
    mechanism: "Trilha Entrada",
    price: 197,
    suggestedAffiliate: 40,
    guaranteeDays: 30,
    bump: "Mentoria em Grupo 1 sessão (R$97)",
    upsell: "Sistema BalcãoIA (R$197)",
    alignedWithBalcaoia: true,
    chapters: ["Como usar", "Ordem", "21 dias", "Sinergia", "Próximo passo"],
    painPoints: ["Não sabe por onde começar", "Compra isolada"],
    benefits: ["Ordem clara", "Economia de trilha", "Base sólida"],
  },
  {
    slug: "mentoria-grupo-gravada",
    logoSlug: "mentoria-grupo-gravada",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_MENTORIA",
    tier: 3,
    title: "Mentoria BalcãoIA em Grupo — Implementação Guiada",
    subtitle: "3 meses de implementação guiada gravada",
    promise: "Mentoria gravada com diagnóstico, plano de ação e comunidade.",
    bigIdea: "Ciclo Mentoria → Tarefa → Revisão",
    mechanism: "Ciclo MTR",
    price: 997,
    suggestedAffiliate: 30,
    guaranteeDays: 15,
    bump: "Análise Individual do Negócio (R$197)",
    upsell: "Curso Avançado + Comunidade (R$1497)",
    alignedWithBalcaoia: true,
    chapters: ["Expectativa", "Diagnóstico", "Operação", "Oferta", "Tempo", "Métricas", "30 dias", "FAQ"],
    painPoints: ["Sozinho na implantação", "Sem revisão", "Travamento"],
    benefits: ["Playbooks", "Ciclo de tarefa", "Gravações"],
  },
  {
    slug: "curso-avancado-comunidade",
    logoSlug: "curso-avancado-comunidade",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_AVANCADO",
    tier: 3,
    title: "Curso Avançado BalcãoIA + Comunidade de Alto Nível",
    subtitle: "Operação avançada com peer review",
    promise: "Nível avançado + comunidade de operadores locais.",
    bigIdea: "Trilha Avançada + Peer Review",
    mechanism: "Peer Review",
    price: 1497,
    suggestedAffiliate: 30,
    guaranteeDays: 15,
    bump: "Revisão Mensal de Estratégia (R$297)",
    upsell: "Certificação BalcãoIA (R$1997)",
    alignedWithBalcaoia: true,
    chapters: ["Operação", "Papéis", "IA governança", "Ofertas", "Retenção", "Comunidade", "Projetos", "Avaliação"],
    painPoints: ["Estagnou no básico", "Sem pares", "Governança fraca"],
    benefits: ["Nível avançado", "Comunidade", "Projetos"],
  },
  {
    slug: "certificado-conclusao-7d",
    logoSlug: "certificado-conclusao-7d",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_CERTIFICACAO",
    tier: 3,
    title: "Certificação BalcãoIA — Especialista em IA para Negócios Locais",
    subtitle: "Credencial por evidência de implantação",
    promise: "Certificação por portfólio operacional — não diploma vazio.",
    bigIdea: "Portfólio Operacional",
    mechanism: "Prova por Portfólio",
    price: 1997,
    suggestedAffiliate: 30,
    guaranteeDays: 15,
    bump: "Kit de Prospecção Completo (R$197)",
    upsell: "Mastermind BalcãoIA (R$2497)",
    alignedWithBalcaoia: true,
    chapters: ["Critérios", "Teoria", "Prática", "Portfólio", "Rubrica", "Defesa", "Manutenção"],
    painPoints: ["Quer credencial vazia", "Sem evidência", "Sem padrão"],
    benefits: ["Rubrica clara", "Portfólio", "Selo por evidência"],
  },
  {
    slug: "mastermind-gravado-operadores",
    logoSlug: "mastermind-gravado-operadores",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_MASTERMIND",
    tier: 3,
    title: "Mastermind BalcãoIA — Grupo Seleto de Alto Nível",
    subtitle: "Rodadas de decisão e accountability",
    promise: "Mastermind gravado para quem já tem base e quer escala ética.",
    bigIdea: "Rodadas de Decisão",
    mechanism: "Rodadas + Accountability",
    price: 2497,
    suggestedAffiliate: 30,
    guaranteeDays: 15,
    bump: "Consultoria Individual 1h extra (R$497)",
    upsell: "Suite Completa (R$2997)",
    alignedWithBalcaoia: true,
    chapters: ["Regras", "Oferta", "Operação", "Tempo", "Pessoas", "Trimestre", "Ética"],
    painPoints: ["Decisões isoladas", "Sem pares sérios", "Escala bagunçada"],
    benefits: ["Rodadas", "Accountability", "Ética de marca"],
  },
  {
    slug: "suite-completa-balcaoia",
    logoSlug: "foco-14",
    checkoutEnvKey: "NEXT_PUBLIC_HOTMART_CHECKOUT_SUITE",
    tier: 3,
    title: "Suite Completa BalcãoIA — Acesso Total e Vitalício",
    subtitle: "Todo o ecossistema em um investimento único",
    promise: "Acesso vitalício a todos os produtos do ecossistema BalcãoIA.",
    bigIdea: "Acesso Total",
    mechanism: "Suite Vitalícia",
    price: 2997,
    suggestedAffiliate: 30,
    guaranteeDays: 30,
    bump: "Licença de Revenda (R$997)",
    upsell: "N/A (produto topo)",
    alignedWithBalcaoia: true,
    chapters: ["O que inclui", "Ordem de uso", "Comunidade", "Suporte", "Atualizações"],
    painPoints: ["Não quer escolher", "Compra fragmentada", "Quer acesso total"],
    benefits: ["14 produtos", "Atualizações", "Suporte prioritário"],
  },
];

export function getVoid9BySlug(slug: string) {
  return VOID9_PORTFOLIO.find((p) => p.slug === slug) ?? null;
}

export function getVoid9AsEbookIdeas(): Array<EbookIdea & { nicheName: string; nicheId: string }> {
  return VOID9_PORTFOLIO.map((p) => ({
    ...p,
    nicheName: `BalcãoIA Tier ${p.tier}`,
    nicheId: "void9-balcaoia",
  }));
}
