/**
 * Portfólio VOID-9 / BalcãoIA — produtos complementares ao Método 7D.
 * Compliance: sem renda garantida; WhatsApp apenas ético/nominativo.
 */
import type { EbookIdea } from "./trends";

export type Void9Product = EbookIdea & {
  tier: 1 | 2 | 3;
  mechanism: string;
  bump: string;
  upsell: string;
  logoSlug: string;
  guaranteeDays: number;
};

export const VOID9_PORTFOLIO: Void9Product[] = [
  {
    slug: "foco-14",
    logoSlug: "foco-14",
    tier: 1,
    title: "FOCO 14 — Rotina de Alta Clareza",
    subtitle: "14 dias para proteger 2 janelas de foco e fechar o dia com evidência",
    promise:
      "Em 14 dias, proteja 2 janelas de foco e feche cada dia com evidência do que avançou — sem virar monge.",
    bigIdea: "Método B.A.L.C.ÃO Foco: Bloqueio, Agenda, Lista 3, Check-out, Âncora, Output",
    mechanism: "B.A.L.C.ÃO Foco",
    price: 67,
    suggestedAffiliate: 50,
    guaranteeDays: 7,
    bump: "Pack Interrupção Zero (R$27)",
    upsell: "Método BalcãoIA 7D + Studio",
    alignedWithBalcaoia: true,
    chapters: [
      "Por que produtividade genérica falha no balcão",
      "Método B.A.L.C.ÃO Foco",
      "2 janelas protegidas",
      "Agenda de interrupções ética",
      "Lista 3",
      "Check-out 10 min",
      "Âncora semanal",
      "Output nomeável",
      "Semana 1 implantação",
      "Semana 2 estabilização",
      "Métricas simples",
      "Manutenção pós dia 14",
    ],
    painPoints: [
      "Dia cheio e pouca evidência do que saiu",
      "WhatsApp derruba qualquer bloco de foco",
      "Lista infinita sem prioridade",
      "Culpa noturna sem fechamento",
    ],
    benefits: [
      "Janelas de foco realistas",
      "Scripts de status ético",
      "Check-out diário",
      "Plano de 14 dias aplicável",
    ],
  },
  {
    slug: "rotina-clareza-freelancer",
    logoSlug: "rotina-clareza-freelancer",
    tier: 1,
    title: "Clareza Semanal",
    subtitle: "Ritual de 1 hora para priorizar a semana",
    promise: "Uma hora por semana para priorizar 3 frentes e bloquear a semana — sem improviso eterno.",
    bigIdea: "Ritual Clareza 4P: Pausar, Priorizar, Planejar, Proteger",
    mechanism: "Clareza 4P",
    price: 47,
    suggestedAffiliate: 50,
    guaranteeDays: 7,
    bump: "Templates de bloco (R$17)",
    upsell: "FOCO 14",
    alignedWithBalcaoia: true,
    chapters: ["Diagnóstico", "4P", "Prioridade tripla", "Calendário", "Buffer", "Revisão", "Casos", "90 dias"],
    painPoints: ["Semana sem plano", "Troca constante de contexto", "Promessas demais"],
    benefits: ["Ritual semanal", "3 frentes claras", "Calendário realista"],
  },
  {
    slug: "checklist-atendimento-local",
    logoSlug: "checklist-atendimento-local",
    tier: 1,
    title: "Checklist Master Atendimento Local",
    subtitle: "Checklists operacionais do dia a dia",
    promise: "Checklists para não esquecer o óbvio no atendimento.",
    bigIdea: "Matriz C.A.I.X.A",
    mechanism: "C.A.I.X.A",
    price: 37,
    suggestedAffiliate: 50,
    guaranteeDays: 7,
    bump: "Scripts curtos (R$17)",
    upsell: "Desafio 7D Atendimento",
    alignedWithBalcaoia: true,
    chapters: ["Abertura", "Primeiro contato", "Qualificação", "Orçamento", "Pós-venda", "Reclamação", "Fechamento", "Auditoria"],
    painPoints: ["Esquece passos", "Cada um atende diferente", "Retrabalho"],
    benefits: ["Padronização leve", "Menos falhas", "Auditoria semanal"],
  },
  {
    slug: "desafio-7d-atendimento",
    logoSlug: "desafio-7d-atendimento",
    tier: 1,
    title: "Desafio 7 Dias — Atendimento",
    subtitle: "Estrutura mínima em uma semana",
    promise: "Em 7 dias: horários, scripts e registro mínimo.",
    bigIdea: "Sprint 7D Balcão",
    mechanism: "Sprint 7D",
    price: 57,
    suggestedAffiliate: 50,
    guaranteeDays: 7,
    bump: "Planilha registro (R$19)",
    upsell: "Curso Organização de Atendimento",
    alignedWithBalcaoia: true,
    chapters: ["Dia 1", "Dia 2", "Dia 3", "Dia 4", "Dia 5", "Dia 6", "Dia 7"],
    painPoints: ["Atendimento caótico", "Sem horário", "Sem registro"],
    benefits: ["Sprint guiado", "Scripts", "Consolidação"],
  },
  {
    slug: "whatsapp-etico-negocios",
    logoSlug: "whatsapp-etico-negocios",
    tier: 1,
    title: "WhatsApp Ético para Negócios Locais",
    subtitle: "Atender e vender sem spam e sem gambiarra",
    promise: "Protocolo ético de consentimento, contexto e continuidade no WhatsApp.",
    bigIdea: "Consentimento → Contexto → Continuidade",
    mechanism: "3C Ético",
    price: 77,
    suggestedAffiliate: 50,
    guaranteeDays: 7,
    bump: "Biblioteca de status (R$27)",
    upsell: "Sistema Balcão Proprietário",
    alignedWithBalcaoia: true,
    chapters: ["Mitos", "Consentimento", "Janelas", "Scripts", "Catálogo", "Follow-up", "LGPD", "Erros"],
    painPoints: ["Medo de ban", "Spam interno", "Respostas inconsistentes"],
    benefits: ["Regras claras", "Scripts éticos", "Janelas de resposta"],
  },
  {
    slug: "guia-catalogo-precos",
    logoSlug: "guia-catalogo-precos",
    tier: 1,
    title: "Guia Catálogo & Preços Claros",
    subtitle: "Oferta compreensível em 30 segundos",
    promise: "Organize catálogo e preços para o cliente entender rápido.",
    bigIdea: "Método 3C: Clareza, Comparação, Compromisso",
    mechanism: "3C Catálogo",
    price: 47,
    suggestedAffiliate: 50,
    guaranteeDays: 7,
    bump: "Planilha preços (R$17)",
    upsell: "Checklist Atendimento",
    alignedWithBalcaoia: true,
    chapters: ["Caos", "Estrutura", "Faixas", "Falar preço", "Objeções", "Atualização"],
    painPoints: ["Preço confuso", "Catálogo bagunçado", "Vergonha de cobrar"],
    benefits: ["Estrutura clara", "Pacotes", "Linguagem de preço"],
  },
  {
    slug: "curso-organizacao-atendimento",
    logoSlug: "curso-organizacao-atendimento",
    tier: 2,
    title: "Curso — Organização de Atendimento",
    subtitle: "Do reativo ao previsível",
    promise: "Módulos práticos para operação de atendimento previsível.",
    bigIdea: "Sistema Fluxo Balcão",
    mechanism: "Fluxo Balcão",
    price: 197,
    suggestedAffiliate: 40,
    guaranteeDays: 7,
    bump: "Templates (R$47)",
    upsell: "Programa 8 Semanas",
    alignedWithBalcaoia: true,
    chapters: ["Diagnóstico", "Canais", "SLA", "Scripts", "IA assistida", "Métricas", "Equipe", "Casos", "21 dias", "Manutenção"],
    painPoints: ["Sem SLA", "Equipe desalinhada", "Retrabalho"],
    benefits: ["Fluxo completo", "IA com revisão", "Implantação 21 dias"],
  },
  {
    slug: "programa-8-semanas-balcao",
    logoSlug: "programa-8-semanas-balcao",
    tier: 2,
    title: "Programa 8 Semanas — Balcão",
    subtitle: "Trilha de implantação com rituais",
    promise: "8 semanas de implantação com métricas e revisão.",
    bigIdea: "Trilha 8S BalcãoIA",
    mechanism: "8S BalcãoIA",
    price: 397,
    suggestedAffiliate: 40,
    guaranteeDays: 7,
    bump: "Grupo gravado (R$97)",
    upsell: "Mentoria Grupo Gravada",
    alignedWithBalcaoia: true,
    chapters: ["S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8"],
    painPoints: ["Começa e para", "Sem ritmo", "Sem métrica"],
    benefits: ["Trilha semanal", "Rituais", "Consolidação"],
  },
  {
    slug: "sistema-balcao-proprietario",
    logoSlug: "sistema-balcao-proprietario",
    tier: 2,
    title: "Sistema Balcão Proprietário",
    subtitle: "SOB — Sistema Operacional do Balcão",
    promise: "Método passo a passo para operar o balcão digital com clareza.",
    bigIdea: "SOB em camadas",
    mechanism: "SOB",
    price: 297,
    suggestedAffiliate: 40,
    guaranteeDays: 7,
    bump: "Playbooks (R$67)",
    upsell: "Bundle Entrada Local",
    alignedWithBalcaoia: true,
    chapters: ["Visão", "Atendimento", "Oferta", "Tempo", "Evidência", "Melhoria", "Implantação", "Auditoria"],
    painPoints: ["Sem sistema", "Tudo na cabeça", "Escalada bagunçada"],
    benefits: ["Camadas claras", "Auditoria", "Playbooks"],
  },
  {
    slug: "workshop-ia-atendimento",
    logoSlug: "workshop-ia-atendimento",
    tier: 2,
    title: "Workshop — IA no Atendimento",
    subtitle: "Prompt → Revisar → Registrar",
    promise: "IA para rascunhar respostas com humano no comando.",
    bigIdea: "Loop Prompt → Revisar → Registrar",
    mechanism: "Loop PRR",
    price: 197,
    suggestedAffiliate: 40,
    guaranteeDays: 7,
    bump: "Pack prompts (R$37)",
    upsell: "Curso Avançado + Comunidade",
    alignedWithBalcaoia: true,
    chapters: ["Limites da IA", "Prompts seguros", "Tom", "FAQ", "Revisão", "Erros", "Plano 7 dias"],
    painPoints: ["IA inventa", "Sem revisão", "Tom errado"],
    benefits: ["Loop seguro", "Prompts", "Governança leve"],
  },
  {
    slug: "bundle-entrada-local",
    logoSlug: "bundle-entrada-local",
    tier: 2,
    title: "Bundle Master Entrada Local",
    subtitle: "FOCO 14 + Clareza + Checklist",
    promise: "Pacote de entrada da trilha BalcãoIA com ordem sugerida.",
    bigIdea: "Trilha Entrada",
    mechanism: "Trilha Entrada",
    price: 147,
    suggestedAffiliate: 40,
    guaranteeDays: 7,
    bump: "WhatsApp Ético (desconto)",
    upsell: "Curso Organização",
    alignedWithBalcaoia: true,
    chapters: ["Como usar", "Ordem", "21 dias", "Sinergia", "Próximo passo"],
    painPoints: ["Não sabe por onde começar", "Compra isolada"],
    benefits: ["Ordem clara", "Economia de trilha", "Base sólida"],
  },
  {
    slug: "mentoria-grupo-gravada",
    logoSlug: "mentoria-grupo-gravada",
    tier: 3,
    title: "Mentoria em Grupo Gravada",
    subtitle: "Sessões + playbooks de implantação",
    promise: "Mentoria gravada com ciclo Mentoria → Tarefa → Revisão.",
    bigIdea: "Ciclo MTR",
    mechanism: "Ciclo MTR",
    price: 997,
    suggestedAffiliate: 30,
    guaranteeDays: 15,
    bump: "Office hours (R$197)",
    upsell: "Mastermind Gravado",
    alignedWithBalcaoia: true,
    chapters: ["Expectativa", "Diagnóstico", "Operação", "Oferta", "Tempo", "Métricas", "30 dias", "FAQ"],
    painPoints: ["Sozinho na implantação", "Sem revisão", "Travamento"],
    benefits: ["Playbooks", "Ciclo de tarefa", "Gravações"],
  },
  {
    slug: "curso-avancado-comunidade",
    logoSlug: "curso-avancado-comunidade",
    tier: 3,
    title: "Curso Avançado + Comunidade",
    subtitle: "Operação avançada com peer review",
    promise: "Nível avançado + comunidade de operadores locais.",
    bigIdea: "Trilha Avançada + Peer Review",
    mechanism: "Peer Review",
    price: 1497,
    suggestedAffiliate: 30,
    guaranteeDays: 15,
    bump: "Templates avançados (R$147)",
    upsell: "Certificação",
    alignedWithBalcaoia: true,
    chapters: ["Operação", "Papéis", "IA governança", "Ofertas", "Retenção", "Comunidade", "Projetos", "Avaliação"],
    painPoints: ["Estagnou no básico", "Sem pares", "Governança fraca"],
    benefits: ["Nível avançado", "Comunidade", "Projetos"],
  },
  {
    slug: "certificado-conclusao-7d",
    logoSlug: "certificado-conclusao-7d",
    tier: 3,
    title: "Certificação BalcãoIA 7D",
    subtitle: "Prova por portfólio operacional",
    promise: "Certificação por evidência de implantação — não diploma vazio.",
    bigIdea: "Portfólio Operacional",
    mechanism: "Prova por Portfólio",
    price: 1997,
    suggestedAffiliate: 30,
    guaranteeDays: 15,
    bump: "Revisão 1:1 gravada (R$297)",
    upsell: "Mastermind",
    alignedWithBalcaoia: true,
    chapters: ["Critérios", "Teoria", "Prática", "Portfólio", "Rubrica", "Defesa", "Manutenção"],
    painPoints: ["Quer credencial vazia", "Sem evidência", "Sem padrão"],
    benefits: ["Rubrica clara", "Portfólio", "Selo por evidência"],
  },
  {
    slug: "mastermind-gravado-operadores",
    logoSlug: "mastermind-gravado-operadores",
    tier: 3,
    title: "Mastermind Gravado — Operadores",
    subtitle: "Rodadas de decisão e accountability",
    promise: "Mastermind gravado para quem já tem base e quer escala ética.",
    bigIdea: "Rodadas de Decisão",
    mechanism: "Rodadas + Accountability",
    price: 2497,
    suggestedAffiliate: 30,
    guaranteeDays: 15,
    bump: "War room (R$397)",
    upsell: "Método 7D Suite / Studio",
    alignedWithBalcaoia: true,
    chapters: ["Regras", "Oferta", "Operação", "Tempo", "Pessoas", "Trimestre", "Ética"],
    painPoints: ["Decisões isoladas", "Sem pares sérios", "Escala bagunçada"],
    benefits: ["Rodadas", "Accountability", "Ética de marca"],
  },
];

export function getVoid9BySlug(slug: string) {
  return VOID9_PORTFOLIO.find((p) => p.slug === slug) ?? null;
}

export function getVoid9AsEbookIdeas(): Array<EbookIdea & { nicheName: string; nicheId: string }> {
  return VOID9_PORTFOLIO.map((p) => ({
    ...p,
    nicheName: `BalcãoIA Tier ${p.tier}`,
    nicheId: "void9-balcaoia",
  }));
}
